{% set name = "hybpiper" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/mossmatters/HybPiper/archive/refs/tags/\
        v{{ version }}.tar.gz"
  sha256: 1ecc41ca78af9748ccac04e3d37e2a568fb1e405a8628c78ddb0a2c4c4a12b21

build:
  skip: true # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - setuptools

  host:
    - python >=3.7.0

  run:
    - numpy
    - progressbar2 >=3.38.0
    - exonerate >=2.4.0
    - blast >=2.9.0
    - spades >=3.15.4 # upgrade pyyaml to run correctly with Python 3.10
    - parallel >=20211022
    - bwa >=0.7.17
    - samtools >=1.14
    - diamond >=2.0.11
    - bbmap >=38.44
    - matplotlib-base >=3.3.2
    - seaborn >=0.11.1
    - pebble >=4.6.3
    - psutil >=5.9.0
    - biopython >=1.80
    - mafft >=7.487

test:
  imports:
    - hybpiper.assemble
    - hybpiper.exonerate_hits
    - hybpiper.distribute_reads_to_targets
    - hybpiper.distribute_targets
    - hybpiper.spades_runner
    - hybpiper.gene_recovery_heatmap
    - hybpiper.utils
    - hybpiper.hybpiper_subparsers
    - hybpiper.paralog_retriever
    - hybpiper.retrieve_sequences
    - hybpiper.hybpiper_stats
    - hybpiper.fix_targetfile


about:
    home: "https://github.com/mossmatters/HybPiper"
    license: GPL-3.0+
    license_family: GPL
    license_file: LICENSE.txt
    summary: "HybPiper version 2.1.3"

extra:
    recipe-maintainers:
      - chris jackson chris.jackson@rbg.vic.gov.au
