{% set version = "1.3.0" %}

package:
  name: metawrap-mg
  version: {{ version }}

source:
  # self-reports as 1.3.0, but tag is v1.3
  url: https://github.com/bxlab/metaWRAP/archive/v1.3.tar.gz
  sha256: ffdbccf340dc0b1ebd0ad6f222e3bdef1e22bbd6e4e5156bf93500a3a834dd52

build:
  noarch: generic
  number: 1

requirements:
  run:
    - biopython
    - blas
    - blast
    - bmtagger
    - bowtie2
    - bwa
    - checkm-genome
    - concoct
    - fastqc
    - kraken
    - kraken2
    - krona
    - matplotlib-base
    - maxbin2
    - megahit
    - metabat2
    - openssl
    - pandas
    - perl-bioperl
    - pplacer
    - prokka
    - quast
    - r-ggplot2
    - r-recommended
    - r-reshape2
    - salmon
    - samtools
    - seaborn
    - spades
    - taxator-tk
    - trim-galore

test:
  commands:
    - "metawrap --version | grep 'metaWRAP v={{ version }}'"
    - "metawrap read_qc | grep 'Usage: metaWRAP read_qc'"
    - which config-metawrap

about:
  home: https://github.com/bxlab/metaWRAP
  license: MIT
  summary: "MetaWRAP is a pipeline for genome-resolved metagenomic data analysis"
